### PR TITLE
Add CSV as an output format.

### PR DESCRIPTION
**Pull request by pwalsh**
The key curators want to view and work with the data in spreadsheets, so this CSV output is designed to facilitate that.

### CODE REVIEW

**Comment by pwalsh** [comment]
@akariv can you review.

**Review by akariv — APPROVED** [review]
Looks good.
The grandparent/parent/node structure was derived from anywhere or something of our own?

**Comment by pwalsh** [comment]
> Looks good.
> The grandparent/parent/node structure was derived from anywhere or something of our own?

I just did it based on what Mor required for this export.

**Comment by akariv** [comment]
Cool, thanks.

**Comment by pwalsh** [comment]
@akariv i think I'll change it so it is just level0, level1, and so on so it is not hard coded for a 3 level hierarchy.

**Comment by akariv** [comment]
Yes, I agree that it is probably better.

**Review by akariv — APPROVED** [review]

**Pull request merged**
